on:
  workflow_dispatch:
jobs:  
  examples:
        runs-on: ubuntu-latest
        steps:
            - run: |
                deprecated=true
                if [[ deprecated ]]; then
                    echo "::warning::this is deprecated function"
                fi
