on:
  workflow_dispatch:
    inputs:
      environment:
        description: "choose the environment"
        required: true
        default: "staging"
        type: choice
        options:
        - satging
        - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy app
        run: echo "deploying application.............."
